In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv("customer_shopping_behavior_2.csv")

print(data)

      Customer ID  Age  Gender Item Purchased     Category  \
0               1   55    Male         Blouse     Clothing
1               2   19    Male        Sweater     Clothing
2               3   50    Male          Jeans     Clothing
3               4   21    Male        Sandals     Footwear
4               5   45    Male         Blouse     Clothing
...           ...  ...     ...            ...          ...
3895         3896   40  Female         Hoodie     Clothing
3896         3897   52  Female       Backpack  Accessories
3897         3898   46  Female           Belt  Accessories
3898         3899   44  Female          Shoes     Footwear
3899         3900   52  Female        Handbag  Accessories

      Purchase Amount (USD)       Location Size      Color  Season  \
0                        53       Kentucky    L       Gray  Winter
1                        64          Maine    L     Maroon  Winter
2                        73  Massachusetts    S     Maroon  Spring
3                        90   Rhode Island    M     Maroon  Spring
4                        49         Oregon    M  Turquoise  Spring
...                     ...            ...  ...        ...     ...
3895                     28       Virginia    L  Turquoise  Summer
3896                     49           Iowa    L      White  Spring
3897                     33     New Jersey    L      Green  Spring
3898                     77      Minnesota    S      Brown  Summer
3899                     81     California    M      Beige  Spring

      Review Rating Subscription Status   Shipping Type Discount Applied  \
0               3.1                 Yes         Express              Yes
1               3.1                 Yes         Express              Yes
2               3.1                 Yes   Free Shipping              Yes
3               3.5                 Yes    Next Day Air              Yes
4               2.7                 Yes   Free Shipping              Yes
...             ...                 ...             ...              ...
3895            4.2                  No  2-Day Shipping               No
3896            4.5                  No    Store Pickup               No
3897            2.9                  No        Standard               No
3898            3.8                  No         Express               No
3899            3.1                  No    Store Pickup               No

     Promo Code Used  Previous Purchases Payment Method Frequency of Purchases
0                Yes                  14          Venmo            Fortnightly
1                Yes                   2           Cash            Fortnightly
2                Yes                  23    Credit Card                 Weekly
3                Yes                  49         PayPal                 Weekly
4                Yes                  31         PayPal               Annually
...              ...                 ...            ...                    ...
3895              No                  32          Venmo                 Weekly
3896              No                  41  Bank Transfer              Bi-Weekly
3897              No                  24          Venmo              Quarterly
3898              No                  24          Venmo                 Weekly
3899              No                  33          Venmo              Quarterly

[3900 rows x 18 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [ ]:
data.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [ ]:
data.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [ ]:
data.columns = data.columns.str.lower()
data.columns = data.columns.str.replace(" ","_")
data.columns = data.columns.str.strip()

In [ ]:
data.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [ ]:
data = data.rename(columns={"purchase_amount_(usd)":"purchase_amount"})

In [ ]:
data.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [ ]:
data.isnull().sum()

customer_id                0
age                        0
gender                     0
item_purchased             0
category                   0
purchase_amount            0
location                   0
size                       0
color                      0
season                     0
review_rating             37
subscription_status        0
shipping_type              0
discount_applied           0
promo_code_used            0
previous_purchases         0
payment_method             0
frequency_of_purchases     0
dtype: int64

In [ ]:
data["review_rating"] = data.groupby("category")["review_rating"].transform(lambda x: x.fillna(x.median()))

In [ ]:
data.isnull().sum()

customer_id               0
age                       0
gender                    0
item_purchased            0
category                  0
purchase_amount           0
location                  0
size                      0
color                     0
season                    0
review_rating             0
subscription_status       0
shipping_type             0
discount_applied          0
promo_code_used           0
previous_purchases        0
payment_method            0
frequency_of_purchases    0
dtype: int64

In [ ]:
# Create column age group
labels = ["young","adult","midle_age","senior"]

data["age_group"] = pd.qcut(data["age"],q=4,labels = labels)

In [ ]:
print(data.head(10))

   customer_id  age gender item_purchased     category  purchase_amount  \
0            1   55   Male         Blouse     Clothing               53
1            2   19   Male        Sweater     Clothing               64
2            3   50   Male          Jeans     Clothing               73
3            4   21   Male        Sandals     Footwear               90
4            5   45   Male         Blouse     Clothing               49
5            6   46   Male       Sneakers     Footwear               20
6            7   63   Male          Shirt     Clothing               85
7            8   27   Male         Shorts     Clothing               34
8            9   26   Male           Coat    Outerwear               97
9           10   57   Male        Handbag  Accessories               31

        location size      color  season  review_rating subscription_status  \
0       Kentucky    L       Gray  Winter            3.1                 Yes
1          Maine    L     Maroon  Winter            3.1                 Yes
2  Massachusetts    S     Maroon  Spring            3.1                 Yes
3   Rhode Island    M     Maroon  Spring            3.5                 Yes
4         Oregon    M  Turquoise  Spring            2.7                 Yes
5        Wyoming    M      White  Summer            2.9                 Yes
6        Montana    M       Gray    Fall            3.2                 Yes
7      Louisiana    L   Charcoal  Winter            3.2                 Yes
8  West Virginia    L     Silver  Summer            2.6                 Yes
9       Missouri    M       Pink  Spring            4.8                 Yes

    shipping_type discount_applied promo_code_used  previous_purchases  \
0         Express              Yes             Yes                  14
1         Express              Yes             Yes                   2
2   Free Shipping              Yes             Yes                  23
3    Next Day Air              Yes             Yes                  49
4   Free Shipping              Yes             Yes                  31
5        Standard              Yes             Yes                  14
6   Free Shipping              Yes             Yes                  49
7   Free Shipping              Yes             Yes                  19
8         Express              Yes             Yes                   8
9  2-Day Shipping              Yes             Yes                   4

  payment_method frequency_of_purchases  age_group
0          Venmo            Fortnightly  midle_age
1           Cash            Fortnightly      young
2    Credit Card                 Weekly  midle_age
3         PayPal                 Weekly      young
4         PayPal               Annually  midle_age
5          Venmo                 Weekly  midle_age
6           Cash              Quarterly     senior
7    Credit Card                 Weekly      young
8          Venmo               Annually      young
9           Cash              Quarterly  midle_age

In [ ]:
data[["age","age_group"]]

      age  age_group
0      55  midle_age
1      19      young
2      50  midle_age
3      21      young
4      45  midle_age
...   ...        ...
3895   40      adult
3896   52  midle_age
3897   46  midle_age
3898   44      adult
3899   52  midle_age

[3900 rows x 2 columns]

In [ ]:
# create column purchase frequancy days

frequency_mapping = {
   " fortnightly": 14,
   "weekly": 7,
   "monthly": 30,
   "quarterly": 90,
   "big-weekly": 14,
   "Annually": 365,
   "every 3 month": 90
}

data["purchase_amount_days"] = data["frequency_of_purchases"].map(frequency_mapping)

In [ ]:
data[["purchase_amount_days","frequency_of_purchases"]]

      purchase_amount_days frequency_of_purchases
0                      NaN            Fortnightly
1                      NaN            Fortnightly
2                      NaN                 Weekly
3                      NaN                 Weekly
4                    365.0               Annually
...                    ...                    ...
3895                   NaN                 Weekly
3896                   NaN              Bi-Weekly
3897                   NaN              Quarterly
3898                   NaN                 Weekly
3899                   NaN              Quarterly

[3900 rows x 2 columns]

In [ ]:
data[["discount_applied","promo_code_used"]]

     discount_applied promo_code_used
0                 Yes             Yes
1                 Yes             Yes
2                 Yes             Yes
3                 Yes             Yes
4                 Yes             Yes
...               ...             ...
3895               No              No
3896               No              No
3897               No              No
3898               No              No
3899               No              No

[3900 rows x 2 columns]

In [ ]:
(data["discount_applied"]== data["promo_code_used"]).all()

np.True_

In [ ]:
data = data.drop(columns=["promo_code_used"])

In [ ]:
data.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_amount_days'],
      dtype='object')